### ISSUE TITLE
production 빌드 시 vendor.js 의 파일 사이즈가 너무 큽니다.  약 1 mbytes

### ISSUE THREAD

**Issue by k2hcorp** [minsoon/vue-simple#2]
js library 의 의존성 주입 시 uglfy 제외하거나 code splitting 을 통해서 관리될 수 있어야 겠습니다.

**Comment by minsoon** [comment]
@k2hcorp  
파일 사이즈에 문제가 되고있던 Vuetify, moment 를 제거 및 필요 컴포넌트들만 호출하여 45%정도 줄였습니다. 허나 아직 미심쩍은 부분들이 있어 사용하는 플러그인에 대한 빌드 검증이 필요할 것 같습니다. 

----------------------------------------------------------------------------------------------------
![2018-07-26 1 51 10](https://user-images.githubusercontent.com/14146022/43245193-64e86774-90e8-11e8-9668-f9356ecd3787.png)
<img width="477" alt="2018-07-26 3 20 48" src="https://user-images.githubusercontent.com/14146022/43245202-6eb5bf2c-90e8-11e8-82d1-de51f6ead451.png">
----------------------------------------------------------------------------------------------------
![2018-07-26 3 20 15](https://user-images.githubusercontent.com/14146022/43245247-91efffb6-90e8-11e8-936a-522377c9f595.png)
<img width="478" alt="2018-07-26 3 19 20" src="https://user-images.githubusercontent.com/14146022/43245259-9c4b2774-90e8-11e8-9ada-f8aa226d1604.png">
