### ISSUE TITLE
route.isPublic 문의

### ISSUE THREAD

**Issue by k2hcorp** [minsoon/vue-simple#3]
아래 코드에서 isPublic 이 true 인데 왜 guardRoute 가 실행되는 지 이해가 안됩니다.
guardRoute 는 사용자 쿠키가 있냐 없냐에 따라 login 페이지로 route 를 이동하거나 layout 을 업데이트 하게 되어 있는 데 의도와 다르지 않나요?

```javascript
/**
 * /router/index.js
 */
...
      if (route.isPublic) return guardRoute(to, from, next);
      next();
    }
  }))
});
```

**Comment by minsoon** [comment]
해당 이슈 수정하여 올려두었습니다. 감사합니다:)
